# -*- coding: utf-8 -*-
"""B-class finishing step: compress the main narrative toward ~8,000 words.

Every replacement is verified for exactly one occurrence before any file write.
No numeric value is altered; only prose is tightened and genuinely redundant
material is signposted to the existing supplementary files.
"""
from pathlib import Path

P = Path(r"D:\SX\TMFI_CPI_MR\03_stage3_mvmr\Complete_Manuscript_Draft_TMFI_BMI_CPI_2026-09-18.md")

REPL = []


def add(old, new):
    REPL.append((old, new))


# ---------------------------------------------------------------- Methods ----

# Instrument selection: palindromic-strand paragraph
add(
 '**Strand orientation of the palindromic instruments.** Five of the 93 joint instruments are A/T or G/C variants (rs2867110, rs6807940, rs10501845, rs17001654, rs9304665), and all five were retained because none sits at intermediate allele frequency. For these variants the allele pair carries no strand information, so orientation cannot be recovered from the allele labels: an allele-matching rule returns "aligned" for every one of them, because both possible assignments match, and the outcome then depends only on the order in which each source file happens to list its two alleles. We therefore resolved orientation from allele frequency, assigning each source allele to whichever strand places its frequency closest to the TMFI frequency. TMFI was used as the anchor because it comes from the UK Biobank imaging cohort and agrees closely with the 1000 Genomes EUR panel (mean |ΔEAF| = 0.017 across the 93 instruments), whereas the GIANT BMI frequency column is a multi-cohort average with deviations up to 0.12 \u2014 large enough to misassign a strand if used on its own. Relative to allele matching, this rule reversed the BMI sign at three variants (rs6807940, rs10501845, rs17001654) and the outcome sign at two (rs6807940, rs9304665); the remaining palindromic variants were unaffected. Every estimate reported here uses the frequency-resolved orientation, and the per-variant decisions are carried in the harmonized instrument tables (Supplementary Table S1). For completeness, under allele matching the BMI direct effect would have been 0.266 (95% CI 0.115\u20130.418; P=0.00058) for `CPI_full` and 0.294 (0.124\u20130.464; P=0.00069) for `CPI_no_imaging`, with TMFI at \u22120.008 (\u22120.056 to 0.040; P=0.744) and \u22120.017 (\u22120.070 to 0.037; P=0.540). Both routes give a positive, significant BMI effect and a null TMFI effect, so no conclusion in this paper depends on how the five palindromic variants were oriented.',
 '**Strand orientation of the palindromic instruments.** Five of the 93 joint instruments are A/T or G/C variants (rs2867110, rs6807940, rs10501845, rs17001654, rs9304665), all retained because none sits at intermediate allele frequency. For these the allele pair carries no strand information \u2014 an allele-matching rule returns "aligned" for every one, and the result then depends only on the order in which each file lists its two alleles \u2014 so we resolved orientation from allele frequency, assigning each source allele to whichever strand places its frequency closest to the TMFI frequency. TMFI was the anchor because it comes from the UK Biobank imaging cohort and agrees closely with the 1000 Genomes EUR panel (mean |\u0394EAF| = 0.017 across the 93 instruments), whereas the GIANT BMI frequency column is a multi-cohort average with deviations up to 0.12, large enough to misassign a strand if used alone. Relative to allele matching this reversed the BMI sign at three variants (rs6807940, rs10501845, rs17001654) and the outcome sign at two (rs6807940, rs9304665); per-variant decisions are archived in Supplementary Table S1. Under allele matching instead, the BMI direct effect would have been 0.266 (95% CI 0.115\u20130.418; P=0.00058) for `CPI_full` and 0.294 (0.124\u20130.464; P=0.00069) for `CPI_no_imaging`, with TMFI at \u22120.008 (\u22120.056 to 0.040; P=0.744) and \u22120.017 (\u22120.070 to 0.037; P=0.540). Both routes give a positive, significant BMI effect and a null TMFI effect, so no conclusion in this paper depends on how the five palindromic variants were oriented.',
)

# Instrument selection: Stage 1 panel-coverage paragraph
add(
 'Stage 1 applied this procedure to the TMFI candidates alone, producing 42 independent instruments from 3,838 clean rsID-annotated candidates. Only 873 of those candidates (22.75%) were present in the EUR reference panel (1,836,406 variants; 503 individuals); the remaining 2,965 were absent and were re-checked by chromosome-position matching to exclude rsID aliasing as the cause. Missing variants had a lower median minor allele frequency than present ones (0.264 vs 0.324), so absence is not fully explained by low frequency. This coverage limit does not invalidate clumping among the 42 retained variants, all of which were in the panel, but it could have caused additional eligible signals to be missed; we therefore treat it as a disclosed instrument-selection limitation rather than a resolved one.',
 'Stage 1 applied this procedure to the TMFI candidates alone, producing 42 independent instruments from 3,838 clean rsID-annotated candidates. Only 873 of those candidates (22.75%) were present in the EUR reference panel (1,836,406 variants; 503 individuals); the remaining 2,965 were absent and re-checked by chromosome-position matching to exclude rsID aliasing. Missing variants had lower median minor allele frequency than present ones (0.264 vs 0.324), so absence is not fully explained by low frequency. This does not invalidate clumping among the 42 retained variants, all of which were in the panel, but eligible signals outside it may have been missed; we treat this as a disclosed limitation rather than a resolved one.',
)

# Power / implied SD
add(
 'This gave sd<sub>TMFI</sub>=2.03, sd<sub>CPI_full</sub>=2.89 and sd<sub>CPI_no_imaging</sub>=2.93 units. The same estimator applied to the BMI file returns 1.23, but that number is not the exposure SD: the GIANT coefficients are already per SD of BMI, and the file\'s single-trait LD score intercept of 0.62 (Table 7, Panel B) shows that its reported standard errors are roughly 27% larger than the sampling expectation, which is exactly what inflates the implied value. Removing that inflation returns 0.97\u20131.02, and we therefore used sd<sub>BMI</sub>=1.00 by definition; the evidence for this is set out immediately below. Effects are therefore expressed as SD change in pain intensity per SD change in exposure, which also removes dependence on the unverified physical TMFI unit. Raw-scale coefficients are reported alongside all standardized values. The same estimator and the same TMFI standard deviation were applied in Stage 1, so the two stages are directly comparable.',
 'This gave sd<sub>TMFI</sub>=2.03, sd<sub>CPI_full</sub>=2.89 and sd<sub>CPI_no_imaging</sub>=2.93 units. Applied to the BMI file the same estimator returns 1.23, but that is not the exposure SD: the GIANT coefficients are already per SD of BMI, and the file\'s single-trait LD score intercept of 0.62 (Table 7, Panel B) shows its reported standard errors are roughly 27% larger than the sampling expectation, which is what inflates the implied value; removing that inflation returns 0.97\u20131.02, so we used sd<sub>BMI</sub>=1.00 by definition (evidence set out immediately below). Effects are therefore expressed as SD change in pain intensity per SD change in exposure, which also removes dependence on the unverified physical TMFI unit; raw-scale coefficients are reported alongside all standardized values. The same estimator and TMFI standard deviation were applied in Stage 1, so the two stages are directly comparable.',
)

# BMI scale section
add(
 'The exposure SD for BMI determines every standardized BMI coefficient in the paper, so it was not taken from the implied-SD estimator uncritically. Three independent checks agree that the GIANT coefficients are expressed per SD of BMI rather than per kg/m\u00b2. First, at loci with published per-allele effects the file returns 0.059 at TMEM18 (rs2867125), 0.055 at MC4R (rs571312) and 0.048 at SEC16B (rs543874), which match the SD-unit values (0.065, 0.046, 0.046) and not the kg/m\u00b2 values (0.31, 0.22, 0.22). Second, the 71 independent genome-wide-significant loci retained after 1 Mb clumping explain \u03a32f(1\u2212f)\u03b2\u00b2 = 0.023 units of variance, against the 2.7% of BMI variance reported for the 97 GIANT loci \u2014 a match under a per-SD scale and a 23-fold discrepancy under a kg/m\u00b2 scale, which would require 0.62. Third, the implied-SD estimator is internally consistent for the other three sources (TMFI single-trait intercept 0.996, CPI_full 1.003), so its BMI value of 1.23\u20131.29 is the per-SD value inflated by the same 1.26-fold factor that depresses the BMI intercept to 0.62. We therefore set sd<sub>BMI</sub>=1.00. The alternative, dividing the implied value by the inflation factor, gives 0.97\u20131.02 and changes nothing reported here by more than 3%.',
 'The exposure SD for BMI determines every standardized BMI coefficient in the paper, so it was not taken from the implied-SD estimator uncritically. Three independent checks agree that the GIANT coefficients are per SD of BMI rather than per kg/m\u00b2. First, at loci with published per-allele effects the file returns 0.059 at TMEM18 (rs2867125), 0.055 at MC4R (rs571312) and 0.048 at SEC16B (rs543874), matching the SD-unit values (0.065, 0.046, 0.046) and not the kg/m\u00b2 values (0.31, 0.22, 0.22). Second, the 71 independent genome-wide-significant loci retained after 1 Mb clumping explain \u03a32f(1\u2212f)\u03b2\u00b2 = 0.023 of variance, against the 2.7% reported for the 97 GIANT loci \u2014 a match under a per-SD scale and a 23-fold discrepancy under kg/m\u00b2, which would require 0.62. Third, the implied-SD estimator is internally consistent for the other three sources (TMFI single-trait intercept 0.996, CPI_full 1.003), so its BMI value of 1.23\u20131.29 is the per-SD value inflated by the same 1.26-fold factor that depresses the BMI intercept to 0.62. We therefore set sd<sub>BMI</sub>=1.00; dividing the implied value by the inflation factor instead gives 0.97\u20131.02 and changes nothing reported here by more than 3%.',
)

# LD score method, first paragraph
add(
 'Both UK Biobank-derived datasets \u2014 TMFI and CPI \u2014 necessarily draw on overlapping participants, and in two-sample MR such overlap biases estimates toward the confounded observational association. Because only summary statistics are public, we quantified the overlap rather than asserting it. We computed LD scores from the 1000 Genomes European panel (503 individuals; 1,836,406 variants; \u00b1500 kb windows; r\u00b2 shrunk by max(0, r\u00b2\u2212(1\u2212r\u00b2)/(n\u22122)); each SNP pair counted once and credited to both partners; M = 1,733,894 polymorphic variants underlying the regression), harmonised all four sets of summary statistics against that panel allowing allele swap and strand complement with palindromic variants excluded, and fitted single-trait and cross-trait LD score regression [10] by OLS followed by two-step weighted least squares with a 200-block delete-one jackknife. Under this model the cross-trait intercept equals N_shared\u00b7\u03c1_phen/\u221a(N_kN_m), which is exactly the sampling covariance that generates the MR bias.',
 'Both UK Biobank-derived datasets \u2014 TMFI and CPI \u2014 necessarily draw on overlapping participants, and in two-sample MR such overlap biases estimates toward the confounded observational association; because only summary statistics are public, we quantified the overlap rather than asserting it. LD scores were computed from the 1000 Genomes European panel (503 individuals; 1,836,406 variants; \u00b1500 kb windows; r\u00b2 shrunk by max(0, r\u00b2\u2212(1\u2212r\u00b2)/(n\u22122)); each SNP pair counted once and credited to both partners; M = 1,733,894 polymorphic variants), all four sets of summary statistics were harmonised against that panel allowing allele swap and strand complement with palindromic variants excluded, and single-trait and cross-trait LD score regression [10] was fitted by OLS followed by two-step weighted least squares with a 200-block delete-one jackknife. Under this model the cross-trait intercept equals N_shared\u00b7\u03c1_phen/\u221a(N_kN_m), exactly the sampling covariance that generates the MR bias.',
)

# LD score method, propagation paragraph
add(
 'The intercept propagates to the reported estimates analytically. Writing X for the matrix of exposure betas and W = diag(1/se_Y\u00b2), the overlap contributes E[X\'W\u03b2_Y] = (X\'WX)\u03b8 + u with u_i = intercept_i\u00b7\u03a3_j(se_Xij/se_Yj), so bias(\u03b8\u0302) = (X\'WX)\u207b\u00b9u; this reduces to the standard univariable expression intercept\u00b7\u03a3(se_X/se_Y)/\u03a3(\u03b2_X\u00b2/se_Y\u00b2) in the single-exposure case. Two properties follow and matter for interpretation. First, the identified quantity is the product N_shared\u00b7\u03c1_phen, which cannot be decomposed into a head-count and a phenotypic correlation without individual-level data; we therefore report the product and impose no assumption on \u03c1_phen. Second, because the bias enters through the noise covariance while the signal enters through \u03b2_X\u00b2, strong instruments dilute it, so a statistically significant intercept need not imply a consequential bias \u2014 which is what we observed. This is the analytic core of MRlap [11], re-implemented here against the exact instrument sets reported above so that each step can be audited.',
 'The intercept propagates to the reported estimates analytically. Writing X for the matrix of exposure betas and W = diag(1/se_Y\u00b2), the overlap contributes E[X\'W\u03b2_Y] = (X\'WX)\u03b8 + u with u_i = intercept_i\u00b7\u03a3_j(se_Xij/se_Yj), so bias(\u03b8\u0302) = (X\'WX)\u207b\u00b9u, reducing to the standard univariable expression intercept\u00b7\u03a3(se_X/se_Y)/\u03a3(\u03b2_X\u00b2/se_Y\u00b2) in the single-exposure case. Two properties matter for interpretation. First, the identified quantity is the product N_shared\u00b7\u03c1_phen, which cannot be decomposed into a head-count and a phenotypic correlation without individual-level data, so we report the product and impose no assumption on \u03c1_phen. Second, the bias enters through the noise covariance while the signal enters through \u03b2_X\u00b2, so strong instruments dilute it and a statistically significant intercept need not imply a consequential bias. This is the analytic core of MRlap [11], re-implemented here against the exact instrument sets reported above so that each step can be audited.',
)

# Effect-size scale of site-matched outcomes
add(
 'Because BOLT-LMM applies a linear model to a 0/1 phenotype, the coefficients distributed by these three sources are risk differences on the absolute-probability scale, not log odds ratios. We verified this on the summary statistics themselves rather than relying on repository metadata: for a linear model the residual variance satisfies SE\u00b2 \u00d7 2Nf(1\u2212f) = \u03bc(1\u2212\u03bc), whereas for a logistic model the same quantity equals 1/[\u03bc(1\u2212\u03bc)]. Across 300,000 variants per outcome the observed values were 0.1678 for knee pain, 0.1904 for back pain and 0.1736 for the second knee-pain specification, against \u03bc(1\u2212\u03bc) = 0.1680 and 0.1907 computed from the case counts reported in the source files (98,704/461,857 and 118,471/461,857) \u2014 agreement to within 0.2% \u2014 and against 5.96 and 5.25, the values a logistic model would have produced. The second knee-pain specification publishes no case count, so \u03bc was estimated from the same identity, giving 0.2236 (about 96,000 cases); because \u03bc enters only through the product \u03bc(1\u2212\u03bc), varying it across 0.18\u20130.28 moves the odds ratios by less than 4% and leaves every P value untouched.',
 'Because BOLT-LMM applies a linear model to a 0/1 phenotype, the coefficients distributed by these three sources are risk differences on the absolute-probability scale, not log odds ratios. We verified this on the summary statistics themselves rather than relying on repository metadata: for a linear model the residual variance satisfies SE\u00b2 \u00d7 2Nf(1\u2212f) = \u03bc(1\u2212\u03bc), whereas for a logistic model the same quantity equals 1/[\u03bc(1\u2212\u03bc)]. Across 300,000 variants per outcome the observed values were 0.1678 for knee pain, 0.1904 for back pain and 0.1736 for the second knee-pain specification, against \u03bc(1\u2212\u03bc) = 0.1680 and 0.1907 from the case counts in the source files (98,704/461,857 and 118,471/461,857) \u2014 agreement within 0.2% \u2014 and against 5.96 and 5.25, the values a logistic model would have produced. The second knee-pain specification publishes no case count, so \u03bc was estimated from the same identity, giving 0.2236 (about 96,000 cases); because \u03bc enters only through the product \u03bc(1\u2212\u03bc), varying it across 0.18\u20130.28 moves the odds ratios by less than 4% and leaves every P value untouched.',
)

add(
 'Odds ratios were therefore obtained with the transformation given in the BOLT-LMM manual, log OR = \u03b2/[\u03bc(1\u2212\u03bc)], with the standard error divided by the same constant (\u03bc = 0.2137 for knee pain, 0.2565 for back pain, 0.2236 for the second knee-pain specification). Two consequences matter for reading Table 8. First, \u03b2 and its standard error are divided by the same constant, so every z statistic, P value, heterogeneity statistic, conditional F statistic, Steiger test and tipping-point calculation in this section is exactly invariant to the transformation; the correction changes odds ratios, confidence intervals, the minimum detectable effect and the absolute magnitude of the overlap bias, and nothing else. Second, the transformation is an approximation valid for small per-allele effects at moderate prevalence, so we also report the underlying risk differences per SD, which require no approximation, in the note to Table 8.',
 'Odds ratios were therefore obtained with the transformation given in the BOLT-LMM manual, log OR = \u03b2/[\u03bc(1\u2212\u03bc)], with the standard error divided by the same constant (\u03bc = 0.2137 for knee pain, 0.2565 for back pain, 0.2236 for the second knee-pain specification). Two consequences matter for reading Table 8. First, because \u03b2 and its standard error are divided by the same constant, every z statistic, P value, heterogeneity statistic, conditional F statistic, Steiger test and tipping-point calculation in this section is exactly invariant to the transformation, which changes only the odds ratios, confidence intervals, minimum detectable effect and absolute magnitude of the overlap bias. Second, the transformation is an approximation valid for small per-allele effects at moderate prevalence, so we also report the underlying risk differences per SD, which require no approximation, in the note to Table 8.',
)

# Independent re-implementation
add(
 'Every estimator applied to the site-matched outcomes was computed twice, by two implementations written independently from the published formulae and sharing only the frozen harmonized input files: the Python pipeline used throughout the preceding stages, and a base-R re-implementation (R 4.5.1) that depends on no third-party package. This was done so that the reported numbers could not be an artefact of a single software implementation.',
 'Every estimator applied to the site-matched outcomes was computed twice, by two implementations written independently from the published formulae and sharing only the frozen harmonized input files: the Python pipeline used in the preceding stages, and a base-R re-implementation (R 4.5.1) depending on no third-party package (Supplementary Table S10).',
)

add(
 'The two implementations agree to at least six significant figures for every primary estimator \u2014 fixed-effect and multiplicative-random-effects inverse-variance weighting, MR-Egger, and both coefficients of the multivariable model. For example, back pain returns OR = 1.01352 (95% CI 0.97171\u20131.05714; P = 0.53196) and knee pain returns a multivariable BMI OR = 1.2751 (1.1772\u20131.3812; P = 2.5 \u00d7 10\u207b\u2079) under both. The agreement extends to the standard errors, not merely to the point estimates, so the confidence intervals and P values in Table 8 are implementation-independent.',
 'The two agree to at least six significant figures for every primary estimator \u2014 fixed-effect and multiplicative-random-effects inverse-variance weighting, MR-Egger, and both coefficients of the multivariable model \u2014 and the agreement extends to the standard errors, not merely to the point estimates, so the confidence intervals and P values in Table 8 are implementation-independent. For example, back pain returns OR = 1.01352 (95% CI 0.97171\u20131.05714; P = 0.53196) and knee pain a multivariable BMI OR = 1.2751 (1.1772\u20131.3812; P = 2.5 \u00d7 10\u207b\u2079) under both.',
)

add(
 'One estimator did differ between the two implementations. The weighted median is not uniquely defined at the level of implementation: the two codes adopt different conventions for interpolation at the median and for the standard error (analytic versus resampling). Across the three outcomes the weighted-median odds ratios span 1.0042\u20131.0086 for back pain, 1.0309\u20131.0424 for knee pain and 1.0179\u20131.0201 for the second knee-pain specification, with P \u2265 0.39 for every variant in which a P value was computed. Every convention therefore returns a null, the spread across conventions is an order of magnitude narrower than the confidence intervals reported in Table 8, and no conclusion depends on the choice. We report one convention consistently and archive both implementations with their complete outputs (Supplementary Table S10).',
 'One estimator did differ: the weighted median is not uniquely defined at the level of implementation, the two codes adopting different conventions for interpolation at the median and for the standard error (analytic versus resampling). Across the three outcomes the weighted-median odds ratios span 1.0042\u20131.0086 for back pain, 1.0309\u20131.0424 for knee pain and 1.0179\u20131.0201 for the second knee-pain specification, with P \u2265 0.39 throughout. Every convention returns a null, the spread across conventions is an order of magnitude narrower than the confidence intervals in Table 8, and no conclusion depends on the choice; we report one convention consistently and archive both with their complete outputs (Supplementary Table S10).',
)

# Reproducibility and statistical reporting
add(
 'All estimates, robustness tables and figures were regenerated from the frozen Stage 1, Stage 2, Stage 2B and Stage 3 CSV outputs by `manuscript_numbers.py`, which is the single source of truth for every number quoted here. LD clumping used PLINK v1.9.0-rc2; Stage 1 estimators were implemented directly in R; Stage 2 and Stage 3 used R 4.6.1 with the MVMR package version 0.4.8; harmonization, power and figure code were written in Python 3.13 with NumPy 2.5.1, pandas 3.0.5 and SciPy 1.18.0. The BMI source file was verified before analysis (`SNP_gwas_mc_merge_nogc.tbl.uniq.gz`, 35,869,809 bytes, MD5 `af06523b7d0705a7e5f707599bea7afe`); the LD reference panel files were verified as `1000G_EUR.bed` MD5 `a163c74ea92676c9ada76fe5eb3b2ec9`, `.bim` MD5 `81b1ee40a05ef5be98ad3e496c71d708`, `.fam` MD5 `669a4260fda7a9e1dd7df374aff294ea`. The site-matched stage was estimated twice, by `stage5_mr.py` under Python 3.13 and by the independent base-R re-implementation `stage5_validation_baser.R` under R 4.5.1, and both outputs are archived (Supplementary Table S10).',
 'All estimates, robustness tables and figures were regenerated from the frozen Stage 1, Stage 2, Stage 2B and Stage 3 CSV outputs by `manuscript_numbers.py`, the single source of truth for every number quoted here. LD clumping used PLINK v1.9.0-rc2; Stage 1 estimators were implemented directly in R; Stage 2 and Stage 3 used R 4.6.1 with MVMR 0.4.8; harmonization, power and figure code were written in Python 3.13 with NumPy 2.5.1, pandas 3.0.5 and SciPy 1.18.0. The site-matched stage was estimated twice, by `stage5_mr.py` and by the independent base-R re-implementation `stage5_validation_baser.R` (R 4.5.1), both archived in Supplementary Table S10. Byte sizes and MD5 checksums for every input file, including the BMI source file and the LD reference panel, are given in Supplementary Appendix S1.',
)

add(
 'Confidence intervals and P values follow one declared rule throughout: intervals are estimate \u00b1 1.96 \u00d7 standard error, and P values are two-sided from the standard normal distribution applied to z = \u03b2/SE. The two are therefore mutually consistent \u2014 a reported interval excludes zero exactly when the reported P value is below 0.05, which was not true of the earlier draft, where intervals used the normal quantile and P values the Student t. With 93 instruments and two exposures the t critical value is 1.986 rather than 1.96, so a t convention would widen every Stage 2 interval by about 1.3% and raise the primary BMI P value from 7.5\u00d710\u207b\u2074 to 1.1\u00d710\u207b\u00b3; the difference changes no conclusion, and the interval convention was already the normal one, so the normal rule is applied uniformly and supersedes the earlier mixed exports. The only values not generated under this rule are the two Stage 1 MR-Egger P values, which are those exported by TwoSampleMR using a t distribution with 40 degrees of freedom; the normal rule would give 0.667 and 0.842 in place of 0.670 and 0.843, a difference below 0.003. Raw-scale coefficients are reported alongside all standardized values.',
 'Confidence intervals and P values follow one declared rule throughout: intervals are estimate \u00b1 1.96 \u00d7 standard error, P values two-sided from the standard normal distribution applied to z = \u03b2/SE. The two are therefore mutually consistent \u2014 an interval excludes zero exactly when the reported P value is below 0.05 \u2014 which was not true of an earlier draft in which intervals used the normal quantile and P values the Student t; adopting t throughout would widen every Stage 2 interval by about 1.3% and raise the primary BMI P value from 7.5\u00d710\u207b\u2074 to 1.1\u00d710\u207b\u00b3, changing no conclusion. The only exceptions are the two Stage 1 MR-Egger P values exported by TwoSampleMR using t with 40 degrees of freedom (0.670 and 0.843; the normal rule gives 0.667 and 0.842). Raw-scale coefficients are reported alongside all standardized values.',
)

add(
 'Missing data were handled by complete-case harmonization. A variant was carried into an analysis only if the exposure file, the outcome file and the LD reference panel all supplied a usable allele pair, frequency, effect and standard error for it; variants failing any of these were dropped from that analysis rather than imputed, and the counts resulting from each step are given under Instrument selection and harmonization and in Supplementary Table S1. No multiple-testing correction was applied: the primary contrast is a single pre-specified comparison between two exposures fitted in the same model, the site-matched secondary outcomes were pre-specified as a replication of that contrast rather than as new hypotheses, and the reported P values are interpreted as measures of compatibility with the null rather than as pass/fail decisions at a threshold. The study was not preregistered; the instrument sets, outcome definitions, estimator hierarchy and sensitivity analyses were fixed before the Stage 2 estimates were inspected, and the frozen intermediate files that record this are deposited with the code archive, but no protocol was posted to a public registry.',
 'Missing data were handled by complete-case harmonization: a variant entered an analysis only if the exposure file, outcome file and LD reference panel all supplied a usable allele pair, frequency, effect and standard error, and variants failing any of these were dropped rather than imputed; counts at each step are given under Instrument selection and harmonization and in Supplementary Table S1. No multiple-testing correction was applied, because the primary contrast is a single pre-specified comparison of two exposures fitted in the same model and the site-matched outcomes were pre-specified as a replication of that contrast rather than as new hypotheses. The study was not preregistered: instrument sets, outcome definitions, estimator hierarchy and sensitivity analyses were fixed before the Stage 2 estimates were inspected and the frozen intermediate files recording this are deposited with the code archive, but no protocol was posted to a public registry.',
)

# ---------------------------------------------------------------- Results ----

add(
 'That bound becomes interpretable against the positive control obtained in the same model. The BMI direct effect was estimated at 0.090 SD (`CPI_full`) and 0.101 SD (`CPI_no_imaging`) and was detected with approximately 92% and 93% power, respectively. The minimum TMFI effect detectable at 80% power was therefore about 1.9-fold smaller than the BMI effect the same model recovered. The upper confidence limits exclude any positive TMFI effect larger than 0.031 SD for `CPI_full` and 0.029 SD for `CPI_no_imaging`, corresponding to 35% and 28% of the respective BMI point estimates. Power reached 83% for a 0.05 SD TMFI effect on `CPI_full` and 75% on `CPI_no_imaging`, and exceeded 99% for a 0.075 SD effect on either outcome.',
 'That bound becomes interpretable against the positive control obtained in the same model. The BMI direct effect was 0.090 SD (`CPI_full`) and 0.101 SD (`CPI_no_imaging`), detected with approximately 92% and 93% power, so the minimum TMFI effect detectable at 80% power was about 1.9-fold smaller than the BMI effect the same model recovered. The upper confidence limits exclude any positive TMFI effect larger than 0.031 SD for `CPI_full` and 0.029 SD for `CPI_no_imaging` \u2014 35% and 28% of the respective BMI point estimates. Power reached 83% for a 0.05 SD TMFI effect on `CPI_full` and 75% on `CPI_no_imaging`, and exceeded 99% for a 0.075 SD effect on either outcome.',
)

add(
 '**Transparency note on the sensitivity sets.** The Cook 4/n threshold and the external-target review are not statistically independent for `CPI_full`: the five variants exceeding the Cook threshold (rs2867110, rs731839, rs543874, rs13107325, rs11822234, in descending Cook distance) were exactly the five variants flagged by external review, so the two rows of Table 4 are the same fitted model and must not be counted as two separate replications. For `CPI_no_imaging` the sets diverge \u2014 rs749170 replaces rs13107325 and rs11822234, giving 89 rather than 88 variants and a slightly larger BMI estimate (\u03b2=0.293, 95% CI 0.121\u20130.466) with TMFI still null (\u03b2=\u22120.018, 95% CI \u22120.077\u20130.041). We report this because convergence between a purely statistical influence criterion and an annotation-based criterion is informative in itself: it indicates that the variants with the largest residuals are also those carrying metabolic pleiotropy annotations, rather than being arbitrary high-leverage points.',
 '**Transparency note on the sensitivity sets.** For `CPI_full` the Cook 4/n threshold and the external-target review are not statistically independent: the five variants exceeding the Cook threshold (rs2867110, rs731839, rs543874, rs13107325, rs11822234, in descending Cook distance) were exactly the five flagged by external review, so the two rows of Table 4 are the same fitted model and must not be counted as two separate replications. For `CPI_no_imaging` the sets diverge \u2014 rs749170 replaces rs13107325 and rs11822234, giving 89 rather than 88 variants and a slightly larger BMI estimate (\u03b2=0.293, 95% CI 0.121\u20130.466) with TMFI still null (\u03b2=\u22120.018, 95% CI \u22120.077\u20130.041). That convergence between a purely statistical influence criterion and an annotation-based criterion is itself informative: the variants with the largest residuals are also those carrying metabolic pleiotropy annotations, rather than arbitrary high-leverage points.',
)

add(
 'The modified Q statistic indicated residual instrument heterogeneity for both outcomes: Q=171.48 on 90 degrees of freedom for `CPI_full` (P=5.04\u00d710\u207b\u2077) and Q=163.93 on 90 degrees of freedom for `CPI_no_imaging` (P=3.16\u00d710\u207b\u2076); the corresponding dispersion statistics were \u03c6=1.90 and \u03c6=1.81. Three observations delimit what this heterogeneity can and cannot explain. First, MVMR-Egger intercepts were statistically indistinguishable from zero, so the scatter is not a signature of unbalanced directional pleiotropy. Second, the two exposures move in opposite directions, which balanced noise across instruments cannot manufacture. Third, the fixed-effect fit reproduces both point estimates almost exactly, so heterogeneity inflates variance rather than shifting estimates. The Q result therefore limits a claim of complete instrument validity and motivates caution about absolute magnitudes, but it does not provide a mechanism that would convert a genuinely null TMFI effect into the present data.',
 'The modified Q statistic indicated residual instrument heterogeneity for both outcomes: Q=171.48 on 90 degrees of freedom for `CPI_full` (P=5.04\u00d710\u207b\u2077) and Q=163.93 on 90 degrees of freedom for `CPI_no_imaging` (P=3.16\u00d710\u207b\u2076); dispersion statistics were \u03c6=1.90 and \u03c6=1.81. Three observations delimit what this can and cannot explain: MVMR-Egger intercepts were indistinguishable from zero, so the scatter is not a signature of unbalanced directional pleiotropy; the two exposures move in opposite directions, which balanced noise across instruments cannot manufacture; and the fixed-effect fit reproduces both point estimates almost exactly, so heterogeneity inflates variance rather than shifting estimates. The Q result therefore limits a claim of complete instrument validity and motivates caution about absolute magnitudes, but provides no mechanism that would convert a genuinely null TMFI effect into the present data.',
)

add(
 'We therefore also inverted the question. Because the cross-trait intercept equals N_shared\u00b7\u03c1_phen/\u221a(N_kN_m) with |\u03c1_phen|\u22641 and N_shared\u2264min(N_k,N_m), no configuration of overlapping participants can produce an intercept larger than \u221a(min/max). For CPI_full this structural ceiling is 0.587 for the TMFI path and 0.765 for the BMI path; for CPI_no_imaging it is 0.659 and 0.681. Using the standard errors reported in Table 3, the intercept required to move the TMFI effect to significance, or the BMI effect to non-significance, was 1.27, 1.24, 1.03 and 1.28 respectively \u2014 in every case above the corresponding ceiling. This ceiling argument is a sensitivity analysis under stated assumptions rather than a proof: it takes the intercepts as estimated without error and treats the reported standard errors as the relevant reversal threshold. Under those assumptions, no configuration of overlapping participants \u2014 including complete overlap with perfectly correlated phenotypes \u2014 attained an intercept large enough to reverse either Stage 2 finding.',
 'We therefore also inverted the question. Because the cross-trait intercept equals N_shared\u00b7\u03c1_phen/\u221a(N_kN_m) with |\u03c1_phen|\u22641 and N_shared\u2264min(N_k,N_m), no configuration of overlapping participants can produce an intercept larger than \u221a(min/max): for CPI_full the structural ceiling is 0.587 for the TMFI path and 0.765 for the BMI path; for CPI_no_imaging it is 0.659 and 0.681. Using the standard errors in Table 3, the intercept required to move the TMFI effect to significance, or the BMI effect to non-significance, was 1.27, 1.24, 1.03 and 1.28 respectively \u2014 above the corresponding ceiling in every case. This is a sensitivity analysis under stated assumptions rather than a proof: it takes the intercepts as estimated without error and treats the reported standard errors as the reversal threshold. Under those assumptions no configuration of overlapping participants, including complete overlap with perfectly correlated phenotypes, attained an intercept large enough to reverse either Stage 2 finding.',
)

# ------------------------------------------------------------- Discussion ----

add(
 'Across two stages, two outcome definitions and every robustness specification we fitted, genetically predicted BMI showed a positive association with chronic pain intensity while genetically predicted thigh muscle fat infiltration showed no evidence of an effect, either as a total effect or as an effect conditional on BMI. The contribution of this paper is not that it separates one signal from another \u2014 Stage 1 already showed no detectable TMFI total effect \u2014 but that it converts that null into a quantitative statement. The same model that returned a null TMFI estimate recovered a BMI effect of 0.090 SD per SD with approximately 92% power, while retaining 80% power for a TMFI effect as small as 0.048 SD per SD. The confidence intervals therefore exclude any positive TMFI effect larger than about one quarter of the BMI effect.',
 'Across two stages, two outcome definitions and every robustness specification we fitted, genetically predicted BMI showed a positive association with chronic pain intensity while genetically predicted thigh muscle fat infiltration showed no evidence of an effect, either as a total effect or as one conditional on BMI. The contribution is not that it separates one signal from another \u2014 Stage 1 already showed no detectable TMFI total effect \u2014 but that it converts that null into a quantitative statement: the same model that returned a null TMFI estimate recovered a BMI effect of 0.090 SD per SD with approximately 92% power, while retaining 80% power for a TMFI effect as small as 0.048 SD per SD. The confidence intervals therefore exclude any positive TMFI effect larger than about one quarter of the BMI effect.',
)

add(
 'The exposure contrast was stable under leave-one-out analysis, Huber-IRLS reweighting, Cook-distance exclusions and targeted removal of five review-priority variants; precision changed modestly, the pattern did not. The diagnostics bound what can be claimed rather than merely qualifying it. The modified Q statistics were strongly positive, so absolute magnitudes should not be over-interpreted; the MVMR-Egger intercepts were indistinguishable from zero, providing no evidence of average directional pleiotropy although pleiotropic bias cannot be excluded; the fixed-effect fit reproduced both point estimates, so heterogeneity inflates variance rather than shifting estimates; and conditional F statistics of 22.12 and 35.23 reduce concern about severe conditional weak-instrument bias without excluding it.',
 'The exposure contrast was stable under leave-one-out analysis, Huber-IRLS reweighting, Cook-distance exclusions and targeted removal of five review-priority variants; precision changed modestly, the pattern did not. The diagnostics bound what can be claimed rather than merely qualifying it: the modified Q statistics were strongly positive, so absolute magnitudes should not be over-interpreted; the MVMR-Egger intercepts were indistinguishable from zero, providing no evidence of average directional pleiotropy although pleiotropic bias cannot be excluded; the fixed-effect fit reproduced both point estimates, so heterogeneity inflates variance rather than shifting estimates; and conditional F statistics of 22.12 and 35.23 reduce concern about severe conditional weak-instrument bias without excluding it.',
)

# Limitations
add(
 'Second, the LD reference panel used throughout comprised 503 European individuals covering 1.84 million variants \u2014 considerably smaller than panels derived from within-cohort subsamples \u2014 and it contained only 22.75% of the TMFI candidate variants, so eligible instruments outside the panel may have been missed, although every retained variant was present in it. This affects the absolute heritability estimates, and re-clumping against a denser panel remains worthwhile; the inference used here does not depend on it, because the nested-subset positive control recovered known near-complete overlap to within 2% and the cross-trait intercept is invariant to rescaling of the LD scores.',
 'Second, the LD reference panel comprised 503 European individuals covering 1.84 million variants \u2014 smaller than panels derived from within-cohort subsamples \u2014 and contained only 22.75% of the TMFI candidate variants, so eligible instruments outside it may have been missed, although every retained variant was present. Re-clumping against a denser panel remains worthwhile; the inference here does not depend on it, because the nested-subset positive control recovered near-complete overlap to within 2% and the cross-trait intercept is invariant to rescaling of the LD scores.',
)

add(
 'Fifth, the GIANT BMI release had been genomic-control corrected before distribution (\u03bb=1.61 inferred from its own single-trait intercept), so intercepts involving BMI required rescaling and were additionally stress-tested over assumed non-negative values; a rigorous correction would require the per-cohort \u03bb. The same correction inflates the released standard errors by about 27%, which is why the exposure SD for BMI is set to 1.00 by definition rather than taken from the implied-SD estimator (Methods), and why the conditional F statistics reported for BMI are conservative by a factor of about 1.6.',
 'Fifth, the GIANT BMI release had been genomic-control corrected before distribution (\u03bb=1.61 inferred from its own single-trait intercept), so intercepts involving BMI required rescaling and were stress-tested over assumed non-negative values; a rigorous correction would require the per-cohort \u03bb. The same correction inflates the released standard errors by about 27%, which is why the exposure SD for BMI is set to 1.00 by definition rather than taken from the implied-SD estimator (Methods), and why the conditional F statistics reported for BMI are conservative by a factor of about 1.6.',
)

add(
 'Sixth, the second knee-pain source, used as a same-cohort concordance check on the univariable null returned a BMI association in the opposite direction to the epidemiological expectation (OR per SD 0.905, 95% CI 0.840\u20130.974, P=0.008) under the same instruments, most plausibly because that GWAS adjusted for adiposity-related covariates; it is therefore used only to replicate the TMFI null, and its BMI coefficient is not interpreted.',
 'Sixth, the second knee-pain source, used as a same-cohort concordance check on the univariable null, returned a BMI association opposite to the epidemiological expectation (OR per SD 0.905, 95% CI 0.840\u20130.974, P=0.008) under the same instruments, most plausibly because that GWAS adjusted for adiposity-related covariates; it is therefore used only to check the TMFI null, and its BMI coefficient is not interpreted.',
)

add(
 'Seventh, the three site-matched outcome sources are BOLT-LMM analyses of a binary phenotype, so the odds ratios in Table 8 rest on the approximate conversion log OR = \u03b2/[\u03bc(1\u2212\u03bc)] given in the BOLT-LMM manual, which is exact only for small per-allele effects at moderate prevalence, and the case fraction of the second knee-pain specification is estimated from its standard errors rather than published. The risk differences reported alongside in Table 8 involve no approximation, and every P value, heterogeneity statistic, conditional F statistic and tipping point is invariant to the conversion, so no inference in this paper depends on it. Each of these specifies what a replication study must fix, and none alters the primary contrast.',
 'Seventh, the three site-matched outcome sources are BOLT-LMM analyses of a binary phenotype, so the odds ratios in Table 8 rest on the approximate conversion log OR = \u03b2/[\u03bc(1\u2212\u03bc)] from the BOLT-LMM manual, exact only for small per-allele effects at moderate prevalence, and the case fraction of the second knee-pain specification is estimated from its standard errors rather than published; the risk differences reported alongside in Table 8 involve no approximation, and every P value, heterogeneity statistic, conditional F statistic and tipping point is invariant to the conversion, so no inference depends on it. Each of these specifies what a replication study must fix, and none alters the primary contrast.',
)

# Conclusion
add(
 'Genetically predicted body mass index showed a positive association with chronic pain intensity that persisted after conditioning on thigh muscle fat infiltration, whereas genetically predicted thigh muscle fat infiltration showed no evidence of a total or conditional direct effect. Because the same model recovered the BMI effect at approximately 92% power while retaining 80% power for a TMFI effect of 0.048 SD per SD, this is a bounded null: thigh muscle fat infiltration is unlikely to influence chronic pain intensity at anywhere near the scale of systemic adiposity, although effects below about 0.05 SD per SD remain open. The next decisive test is not another univariable screen but a replication that preserves this joint structure, adds a denser LD reference panel for instrument selection, and extends the conditioning to further correlated muscle traits. The same pattern held for the two site-matched secondary outcomes: genetically predicted thigh muscle fat infiltration showed no evidence of an effect on knee or back pain, while the BMI effect was larger at the weight-bearing joint, and neither result changed materially under the overlap scenarios evaluated. Sample overlap, the one concern that previously could be raised only qualitatively against these analyses, has been quantified here; under the evaluated scenarios it did not come close to reversing either finding, so it need not be the focus of that replication.',
 'Genetically predicted BMI showed a positive association with chronic pain intensity that persisted after conditioning on thigh muscle fat infiltration, whereas genetically predicted thigh muscle fat infiltration showed no evidence of a total or conditional direct effect. Because the same model recovered the BMI effect at approximately 92% power while retaining 80% power for a TMFI effect of 0.048 SD per SD, this is a bounded null: thigh muscle fat infiltration is unlikely to influence chronic pain intensity at anywhere near the scale of systemic adiposity, although effects below about 0.05 SD per SD remain open. The same pattern held for the site-matched outcomes \u2014 no TMFI effect on knee or back pain, a larger BMI effect at the weight-bearing joint, and no material change under the overlap scenarios evaluated. The next decisive test is not another univariable screen but a replication that preserves this joint structure, uses a denser LD reference panel for instrument selection, and extends the conditioning to further correlated muscle traits.',
)


def main():
    t = P.read_text(encoding="utf-8")
    problems = []
    for i, (old, new) in enumerate(REPL):
        c = t.count(old)
        if c != 1:
            problems.append((i, c, old[:110]))
    if problems:
        print("VERIFY FAILED — nothing written")
        for i, c, s in problems:
            print("  #%d occurrences=%d :: %s" % (i, c, s))
        raise SystemExit(1)
    before = len(t.split())
    for old, new in REPL:
        t = t.replace(old, new)
    P.write_text(t, encoding="utf-8")
    print("applied %d replacements" % len(REPL))
    print("whitespace tokens: %d -> %d" % (before, len(t.split())))


if __name__ == "__main__":
    main()
